version: '3.8'

services:
  spring_server:
    image: ${DOCKERHUB_USERNAME}/orange
    container_name: orange
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    volumes:
      - /var/log/spring-boot:/var/log/spring-boot
    networks:
      - my_custom_network

  promtail:
    image: grafana/promtail
    container_name: promtail
    env_file:
      - ../.env
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yml:/promtail-config.yml
      - /var/log/spring-boot:/var/log/spring-boot
    command:
      - -config.file=/promtail-config.yml
      - -config.expand-env=true  # 환경 변수 확장 활성화
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
