version: '3.8'

services:
  spring_server:
    image: ${DOCKERHUB_USERNAME}/orange
    container_name: orange
    env_file:
      - ../${ENV_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - /var/log/spring-boot:/var/log/spring-boot
    networks:
      - my_custom_network

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - "${PROMTAIL_PORT}:${PROMTAIL_PORT}"
    volumes:
      - ./promtail-config.yml:/promtail-config.yml
      - /var/log/spring-boot:/var/log/spring-boot
    command:
      - -config.file=/promtail-config.yml
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
