server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: spring-boot
    static_configs:
      - targets:
        - localhost
        labels:
          job: springboot
          host: ${HOSTNAME} # hostname을 통해 로그 모니터링 시 각 인스턴스 식별
          __path__: /var/log/spring-boot/*.log